from selenium import webdriver
import unittest
import page

class SearchSparkWeb(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Chrome('./chromedriver')
        self.driver.get('https://www.thesparksfoundationsingapore.org')
        self.search_result_page = page.SearchLinkPage(self.driver)

    def test_1_MainPage(self):
        print('-------------------')
        print("Main Page Check")
        print('-----------------\n')
        mainPage = page.MainPage(self.driver)
        assert mainPage.is_title_matches()
        print("> Title Checked")
        assert mainPage.is_header_matches()
        print("> Header Checked")
        mainPage.check_know_more()
        assert self.search_result_page.is_page_load()
        self.driver.back()
        print("> Know More Checked")
        mainPage.check_learn_more()
        assert self.search_result_page.is_page_load()      
        print("> Learn More Checked")
        print("\n-------------------")
        print("Socials Link Check")
        print("-------------------\n")
        assert mainPage.socials_link_check(0, "This page isn't available")
        print("> Facebook Link Checked")
        assert mainPage.socials_link_check(1, "This page is not availabe")
        print("> Linked Link Checked")
        assert mainPage.socials_link_check(2, "Page Not Found")
        print("> Medium Link Checked")
        assert mainPage.socials_link_check(3, "This account doesn't exist")
        print("> Twitter Link Checked")
        assert mainPage.socials_link_check(4, "This site can't be reached")
        print("> Website Link Checked")
        assert mainPage.socials_link_check(5, "Sorry, this page isn't available.")
        print("> Instagram Link Checked")
        print("\n----------------")
        print("Page Check")
        print("-----------------\n")
        self.driver.find_elements_by_class_name("dropdown-toggle")[0].click()
        self.driver.find_elements_by_class_name("dropdown-menu")[0].click()
        assert self.search_result_page.is_page_load()
        print("> About Page Checked")
        self.driver.back()
        self.driver.find_elements_by_class_name("dropdown-toggle")[1].click()
        self.driver.find_elements_by_class_name("dropdown-menu")[1].click()
        assert self.search_result_page.is_page_load()
        print("> Policies Page Checked")
        self.driver.back()
        self.driver.find_elements_by_class_name("dropdown-toggle")[2].click()
        self.driver.find_elements_by_class_name("dropdown-menu")[2].click()
        assert self.search_result_page.is_page_load()
        print("> Programs Page Checked")
        self.driver.back()
        self.driver.find_elements_by_class_name("dropdown-toggle")[3].click()
        self.driver.find_elements_by_class_name("dropdown-menu")[3].click()
        assert self.search_result_page.is_page_load()
        print("> Links Page Checked")
        self.driver.back()
        self.driver.find_elements_by_class_name("dropdown-toggle")[4].click()
        self.driver.find_elements_by_class_name("dropdown-menu")[4].click()
        assert self.search_result_page.is_page_load()
        print("> Join Us Page Checked")
        self.driver.back()

    def tearDown(self):
        self.driver.close()

if __name__ == "__main__":
    unittest.main()